server:
  port: 8080
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost
spring:
  cloud:
    gateway:
      routes:
        - id: usuario-service
          uri: lb://USUARIO-SERVICE
          predicates:
            - Path=/usuario/**
        - id: carro-service
          uri: lb://CARRO-SERVICE
          predicates:
            - Path=/carro/**
        - id: moto-service
          uri: lb://MOTO-SERVICE
          predicates:
            - Path=/moto/**
logging:
  level:
    org.springframework.cloud.gateway: DEBUG


